vim-jp/vim-vimlparser

LICENSE

https://github.com/ynkdir/vim-vimlparser/issues/17#issuecomment-90005889

Create LICENSE, fix #17.

---

autoload/vimlparser.vim
test/test_command.ok
test/test_command.vim

BANG should be allowed for user defined cmd
fix #20

fix incorrect E477

---

autoload/vimlparser.vim

It's hard to translate it into other language especially if it has static
type system.
The changed line is introduced by #3 but it's just debugging purpose and
we can convert string to list in caller side.

Do not make input flexible needlessly

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Fixes https://github.com/vim-jp/vim-vimlparser/issues/22.

neovim: add rshada/wshada

---

.travis.yml
Makefile

It was initially meant for #46, but that is merged already.
I've worked on it further afterwards.

Revisit Travis config, fix check target, update compiled files

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Ref:
- https://github.com/vim-jp/vim-vimlparser/blob/377b6cd4a901b80e6051ab930583479210f9d729/autoload/vimlparser.vim#L521
- https://github.com/vim-jp/vim-vimlparser/blob/377b6cd4a901b80e6051ab930583479210f9d729/autoload/vimlparser.vim#L3774

linepos type should be dict actually

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Some language (e.g. Go) doesn't support string subscript.

Avoid using string subscript

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

It's difficult (or impossible) to translate into other language (e.g. Go)

Avoid subscript

---

autoload/vimlparser.vim

sry, i didn't push the indent fix.  https://github.com/vim-jp/vim-vimlparser/pull/55#pullrequestreview-50865432

Fix indent

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Follow up of #55
I forgot to change this function... I confirmed there are no same issues in other functions.

Add scope hack for compiler (2)

---

README.mkd

[![codecov](https://codecov.io/gh/vim-jp/vim-vimlparser/branch/master/graph/badge.svg)](https://codecov.io/gh/vim-jp/vim-vimlparser)

add codecov badge

---

.travis.yml

This will run all the checks, not stopping at the first failure.

Travis: use --keep-going with make

---

README.mkd

Current example code doesn't work.

Fix example code in README.mkd

---

LICENSE

Update license description (fixes #84)

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py
test/test1.ok
test/test1.vim

Add *=, /=, %=

---

.codecov.yml
.coveragerc
.travis.yml

Currently it does not get reported: https://travis-ci.org/vim-jp/vim-vimlparser/jobs/560504172#L1728

Fix data_file in .coveragerc

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

from https://github.com/vim-jp/vim-vimlparser/pull/110#discussion_r305403481

Fix undefined variable 'token'

---

.travis.yml
Makefile

Fixes https://github.com/vim-jp/vim-vimlparser/issues/131

ci: test with Python 3 also

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py
test/test_command.ok
test/test_command.vim

fix https://github.com/vim-jp/vim-vimlparser/issues/144

fix(parse): fix read_nonwhite get dead loop

---

.travis.yml

Ref: https://github.com/vim-jp/vim-vimlparser/pull/137#issuecomment-517934299

ci: Travis: branches: only build master branch

---

.travis.yml

I fixed `vint`'s url.
> https://github.com/Kuniwak/vint
> https://github.com/Vimjas/vint

[fix] vint's url

---

README.mkd

See: https://github.com/vim-jp/issues/issues/1359

Migrate travis-ci.org to .com

---

.github/workflows/test.yml
Makefile
js/jscompiler.vim
py/pycompiler.vim
scripts/jscompile.sh
scripts/pycompile.sh
test/run.bat
test/run.sh

I think should make CI generate js and py, rather than manually.

Make CI generate js and py
