vim-jp/vim-vimlparser

autoload/vimlparser.vim
test/test_syncmd.ok
test/test_syncmd.vim

vimlparser fails to parse `if 1 | syntax on | endif` and I fixed it.
it's somewhat workaround fix though...

fix parse :syntax with <bar>

---

test/run.vim

https://github.com/vim-jp/vim-vimlparser/blob/b5f83738ba1baf012b9910487e5e38d577a916a5/autoload/vimlparser.vim#L3391
We know that test test_xxx_colonsharp is failing. But this is not designed behavior clearly. So currently, skip the test.

Skip failing test

---

autoload/vimlparser.vim

vim-vimlparser can be translated into Python and JavaScript which
convert number to boolean implicitly, but it's difficlut to translate it
into other language which doesn't have implicit type conversion.
I actually created translater to Go (ref: #26) by including this change.
(We need more tweak for Go translater, but this change is one of them)
Using s:TRUE/s:FALSE is better not only for translator, but also for
readability.

Use s:TRUE/s:FALSE instead of 1/0

---

autoload/vimlparser.vim
scripts/update_builtin_commands.sh
scripts/update_builtin_commands.vim

Make the script in #29 executable from shell script.
USAGE: ./scripts/update_builtin_commands.sh /path/to/vim/src/ex_cmds.h
Example:
```
$ ./scripts/update_builtin_commands.sh /home/haya14busa/src/github.com/vim/vim/src/ex_cmds.h
Append following lines to s:VimLParser.builtin_commands in autoload/vimlparser.vim
\ {'flags': 'BANG|TRLBAR|SBOXOK|CMDWIN', 'minlen': 5, 'name': 'packloadall', 'parser': 'parse_cmd_common'},
\ {'flags': 'RANGE|EXTRA|NEEDARG|CMDWIN', 'minlen': 3, 'name': 'pyx', 'parser': 'parse_cmd_common'},
\ {'flags': 'RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN', 'minlen': 4, 'name': 'pyxdo', 'parser': 'parse_cmd_common'},
\ {'flags': 'RANGE|EXTRA|NEEDARG|CMDWIN', 'minlen': 7, 'name': 'pythonx', 'parser': 'parse_cmd_common'},
\ {'flags': 'RANGE|FILE1|NEEDARG|CMDWIN', 'minlen': 4, 'name': …
```

Add script for updating builtin_commands table

---

autoload/vimlparser.vim

`s:NIL` が返ってくる場合に `E706` になっていたので修正しました。

fix error for `let a.b.=1`

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py
test/test_modifier_commands.ok
test/test_modifier_commands.vim

[Vim 7.4.213](https://github.com/vim/vim/commit/5803ae6c076b1d61381afe27fcdedac61dd2cda9) で追加された `:nos[wapfile]` コマンドを modifier として追加しました。
7.4.213 時点では省略形は `noswap[file]` ですが [7.4.2127](https://github.com/vim/vim/commit/3bcfca3ab4db415d0e750e00204dd25a91fcee77) で `:nos[wapfile]` に変更されています（doc は https://github.com/vim/vim/commit/7e38ea2fb6a781213c85824dcf9ccb582fbc5c43 で修正）。
また、全ての modifier commands は（テストスクリプトに漏れがなければ） [src/testdir/test_usercommands.vim](https://github.com/vim/vim/blob/c3c766ea8c35f5b2bd45fb3d74d0ae46b2d8c24f/src/testdir/test_usercommands.vim#L52-L54) で確認できます。

Add :nos[wapfile] as modifier

---

autoload/vimlparser.vim
js/vimlfunc.js
js/vimlparser.js
py/vimlfunc.py
py/vimlparser.py

I forgot to update the regex table for Python/JavaScript in #28.
This patch fixes it and also uses more appropriate regex.

Fix USERCMD regex and py/js support

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

This change allow us to translate vimlparser.vim to
other language (e.g. Go) which creates scope in "if" block.

Add scope hack for compiler

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

return FUNC where FUNC returns nothing cannot be translated into
languages which doens't support this functionality (e.g. Go).

Fix return for translation to typed language

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Use _ for go-vimlparser (https://github.com/haya14busa/go-vimlparser)
because Go doesn't allow unused variables.
This change is basically just for Go, but I think it's acceptable.

Use underscore for unused var

---

Makefile

test/ directory exists so it was actually a problem not to mark targets
as PHONY.

Add .PHONY

---

autoload/vimlparser.vim

parameter [input] for StringReader.new might be broken when input contain \n

fix vimlparser#test

---

.codecov.yml
.coveragerc
.travis.yml
Makefile
scripts/install-vim.sh
test/run.bat
test/run.sh
test/vimrc

https://github.com/Vimjas/covimerage

Introduce covimerage for test coverage

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

It's convenient to ensure that all node have position data.
Currently, only NODE_TOPLEVEL doesn't have position.
btw, I want to write unite tests, but vimlparser doesn't setup writing unit tests.
maybe we should file a bug and setup testing framework?
e.g. use https://github.com/thinca/vim-themis or create something like runtest.vim in Vim.

Add pos to NODE_TOPLEVEL

---

test/run.vim

1. use buftype=nofile (with enew) to allow for easier `:q` in case of
failures
2. use "diff -u" and use its output in case of failures

Improve test/run.vim

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py
test/test_number.ok
test/test_number.vim

I found Vim script has binary number literals (e.g. 0b0, 0b1011), and they are not supported yet.
Fixed tokenizer to support it.
Sorry, I don't check from when the literal format is supported...

Support binary number literals (e.g. 0b0, 0b1011)

---

.travis.yml

Just a cosmetical change for now, but using jobs allows to tune this further, e.g. by using build stages.

ci: Travis: use jobs with names

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

In Python it would use `ord()`, which does not work for `"\e"`.
But apart from that `viml_char2nr` should probably be made to support/handle `\e`?
(Note however that "\e" is an invalid escape sequence in Python, so should be `r"\e"` there then)

get_token_sq_c: skip char2nr for fixed values

---

js/vimlfunc.js
js/vimlparser.js
py/vimlfunc.py
py/vimlparser.py
test/test1.ok
test/test1.vim

Fix len() for js

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py
test/test_funcname.ok
test/test_funcname.vim

Allow function name which starts with underscore

---

.travis.yml
Makefile

Fixes https://github.com/vim-jp/vim-vimlparser/issues/111.
Alternative to https://github.com/vim-jp/vim-vimlparser/pull/136 - mainly for testing.

ci: run vint on Vim source

---

.travis.yml
autoload/vimlparser.vim
js/jscompiler.vim
py/pycompiler.vim

Fix vint errors

---

.travis.yml
Makefile

* Add `test-fast` task
* Change `test` to `vim/test` and now `make test` runs all test tasks

Makefile: add 'test-fast', change 'test' to 'vim/test' and make 'test'

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

parse_dict_literal_key: use getpos for pos

---

Makefile

Vint tries to import a non-bundled vimlparser first, which we can inject
using `PYTHONPATH`.
Ref: https://github.com/Kuniwak/vint/blob/219501b58c/vint/_bundles/__init__.py#L3-L8

Makefile: checkvim: use own/current vimlparser

---

.coveragerc

Improves performance when tracking (Python) coverage.
Likely needed for covimerage also.

.coveragerc: specific include

---

autoload/vimlparser.vim

I noticed that the changes implementing heredoc introduced `==` again. I think we should use `==#` for consistency.

Use strict comparison operator consistently

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Heredoc was implemented in #120. The current implementation appends string to `rlist` and `body`,
but they should be arrays of `s:Node`. This p/r fixes this typing bugs.

Fix heredoc rlist and body: the type should be s:Node not string

---

autoload/vimlparser.vim
js/vimlparser.js
py/vimlparser.py

Since node.depth is an integer, format specifier should be `%d`, not `%s`. Otherwise go-vimlparser cannot compile.

Fix format specifier for node.depth

---

scripts/jscompile.bat
scripts/jscompile.sh
scripts/pycompile.bat
scripts/pycompile.sh

I noticed that current scripts writes ~/.viminfo. I think it's not intended so I added `-i NONE`.
On the other hand `-E -s` disables reading the default vimrc, but adding `-u NONE` not to rely on this implicit behavior.

Disable default vimrc and viminfo in compile scripts
